/*
 * This file was automatically generated by EvoSuite
 * Tue May 05 19:55:32 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Amount;
import custom_classes.Email;
import custom_classes.Goals;
import custom_classes.Id;
import custom_classes.IncomeDescription;
import custom_classes.TransactionDescription;
import custom_classes.WalletNames;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addAccessAccessEmailPage(Lcustom_classes/Email;)V: Line 144
   * Goal 2. main.ClassUnderTestApogen.addAccessGiveAccessToWalletPage(Lcustom_classes/Email;)V: Line 423
   * Goal 3. main.ClassUnderTestApogen.addProfitSetTotalPage(Lcustom_classes/Amount;)V: Line 606
   * Goal 4. main.ClassUnderTestApogen.cancelHideWalletPage()V: Line 194
   * Goal 5. main.ClassUnderTestApogen.cancelRemoveEmailAccessPage()V: Line 236
   * Goal 6. main.ClassUnderTestApogen.closeAccessEmailPage()V: Line 158
   * Goal 7. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 8. main.ClassUnderTestApogen.editWalletWalletPage(Lcustom_classes/Id;)V: Line 469
   * Goal 9. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 10. main.ClassUnderTestApogen.goToSetTotalPageTransactionsPage()V: Line 390
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsWalletPage(Lcustom_classes/Id;)V: Line 525
   * Goal 12. main.ClassUnderTestApogen.goToWalletPageAddWalletPage()V: Line 347
   * Goal 13. main.ClassUnderTestApogen.goToWalletPageHideWalletPage()V: Line 208
   * Goal 14. main.ClassUnderTestApogen.goToWalletPageTransactionsPage()V: Line 404
   * Goal 15. main.ClassUnderTestApogen.hideWalletWalletPage(Lcustom_classes/Id;)V: Line 562
   * Goal 16. main.ClassUnderTestApogen.manageWalletAccessWalletPage(Lcustom_classes/Id;)V: Line 585
   * Goal 17. main.ClassUnderTestApogen.removeAccessAccessEmailPage(Lcustom_classes/Email;)V: Line 174
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-3164);
      Id id0 = new Id(int0);
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.COMPANY;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.goToWalletPageAddWalletPage();
      classUnderTestApogen0.hideWalletWalletPage(id0);
      classUnderTestApogen0.cancelHideWalletPage();
      classUnderTestApogen0.goToTransactionsWalletPage(id0);
      classUnderTestApogen0.goToSetTotalPageTransactionsPage();
      Amount amount0 = new Amount(id0.value);
      classUnderTestApogen0.addProfitSetTotalPage(amount0);
      classUnderTestApogen0.goToSetTotalPageTransactionsPage();
      classUnderTestApogen0.addProfitSetTotalPage(amount0);
      classUnderTestApogen0.goToSetTotalPageTransactionsPage();
      classUnderTestApogen0.addProfitSetTotalPage(amount0);
      classUnderTestApogen0.goToWalletPageTransactionsPage();
      classUnderTestApogen0.hideWalletWalletPage(id0);
      classUnderTestApogen0.goToWalletPageHideWalletPage();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames1 = WalletNames.COMPANY;
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      int int1 = 2153;
      Id id1 = new Id(int1);
      classUnderTestApogen0.manageWalletAccessWalletPage(id1);
      Email email0 = Email.ASD;
      classUnderTestApogen0.addAccessGiveAccessToWalletPage(email0);
      Email email1 = Email.ASD;
      classUnderTestApogen0.addAccessAccessEmailPage(email1);
      Email email2 = Email.ASD;
      classUnderTestApogen0.removeAccessAccessEmailPage(email2);
      classUnderTestApogen0.cancelRemoveEmailAccessPage();
      Email email3 = Email.COMPANY;
      classUnderTestApogen0.addAccessAccessEmailPage(email3);
      classUnderTestApogen0.removeAccessAccessEmailPage(email2);
      classUnderTestApogen0.cancelRemoveEmailAccessPage();
      classUnderTestApogen0.closeAccessEmailPage();
      classUnderTestApogen0.editWalletWalletPage(id0);
      classUnderTestApogen0.goToWalletPageAddWalletPage();
      int int2 = (-3602);
      Id id2 = new Id(int2);
      classUnderTestApogen0.goToTransactionsWalletPage(id2);
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addIncomeAddIncomePage(Lcustom_classes/IncomeDescription;Lcustom_classes/Amount;)V: Line 41
   * Goal 2. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 3. main.ClassUnderTestApogen.goToAddIncomePageTransactionsPage()V: Line 376
   * Goal 4. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 5. main.ClassUnderTestApogen.goToTransactionsWalletPage(Lcustom_classes/Id;)V: Line 525
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-1582);
      Id id0 = new Id(int0);
      WalletNames walletNames0 = WalletNames.PERSONAL;
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.goToTransactionsWalletPage(id0);
      classUnderTestApogen0.goToAddIncomePageTransactionsPage();
      IncomeDescription incomeDescription0 = IncomeDescription.SCHOLARSHIP;
      int int1 = 209;
      Amount amount0 = new Amount(int1);
      classUnderTestApogen0.addIncomeAddIncomePage(incomeDescription0, amount0);
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addTransactionTransactionsPage(Lcustom_classes/TransactionDescription;Lcustom_classes/Amount;)V: Line 362
   * Goal 2. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 3. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 4. main.ClassUnderTestApogen.goToTransactionsWalletPage(Lcustom_classes/Id;)V: Line 525
   * Goal 5. main.ClassUnderTestApogen.goToTrashPageWalletPage()V: Line 543
   * Goal 6. main.ClassUnderTestApogen.goToWalletPageHideWalletPage()V: Line 208
   * Goal 7. main.ClassUnderTestApogen.goToWalletPageTransactionsPage()V: Line 404
   * Goal 8. main.ClassUnderTestApogen.goToWalletPageTrashPage()V: Line 126
   * Goal 9. main.ClassUnderTestApogen.hideWalletWalletPage(Lcustom_classes/Id;)V: Line 562
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-3396);
      Id id0 = new Id(int0);
      Amount amount0 = new Amount(id0.value);
      TransactionDescription transactionDescription0 = TransactionDescription.EBAY;
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.PRIVATE;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      Id id1 = new Id(id0.value);
      classUnderTestApogen0.hideWalletWalletPage(id1);
      classUnderTestApogen0.goToWalletPageHideWalletPage();
      classUnderTestApogen0.goToTransactionsWalletPage(id0);
      TransactionDescription transactionDescription1 = TransactionDescription.EBAY;
      classUnderTestApogen0.addTransactionTransactionsPage(transactionDescription1, amount0);
      classUnderTestApogen0.addTransactionTransactionsPage(transactionDescription0, amount0);
      classUnderTestApogen0.goToWalletPageTransactionsPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
  }

  //Test case number: 3
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTestApogen.confirmAndSaveCreatePlanAdvancedSettingsPage()V: Line 263
   * Goal 2. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 3. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 4. main.ClassUnderTestApogen.goToCreateNewPlanPageCreatePlanPage()V: Line 92
   * Goal 5. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 6. main.ClassUnderTestApogen.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(Lcustom_classes/Goals;Lcustom_classes/WalletNames;)V: Line 296
   * Goal 7. main.ClassUnderTestApogen.goToPlanPageCreatePlanBasicSettingsPage()V: Line 314
   * Goal 8. main.ClassUnderTestApogen.goToTrashPageWalletPage()V: Line 543
   * Goal 9. main.ClassUnderTestApogen.goToWalletPageTrashPage()V: Line 126
   * Goal 10. main.ClassUnderTestApogen.goToWalletPageViewPlanPage()V: Line 451
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.PERSONAL;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      Goals goals0 = Goals.CAR;
      classUnderTestApogen0.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(goals0, walletNames0);
      classUnderTestApogen0.confirmAndSaveCreatePlanAdvancedSettingsPage();
      classUnderTestApogen0.goToWalletPageViewPlanPage();
  }

  //Test case number: 4
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addProfitSetTotalPage(Lcustom_classes/Amount;)V: Line 606
   * Goal 2. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 3. main.ClassUnderTestApogen.goToAddIncomePageTransactionsPage()V: Line 376
   * Goal 4. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 5. main.ClassUnderTestApogen.goToCreateNewPlanPageCreatePlanPage()V: Line 92
   * Goal 6. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 7. main.ClassUnderTestApogen.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(Lcustom_classes/Goals;Lcustom_classes/WalletNames;)V: Line 296
   * Goal 8. main.ClassUnderTestApogen.goToPlanBasicSettingsPageCreatePlanAdvancedSettingsPage()V: Line 278
   * Goal 9. main.ClassUnderTestApogen.goToPlanPageCreatePlanBasicSettingsPage()V: Line 314
   * Goal 10. main.ClassUnderTestApogen.goToSetTotalPageTransactionsPage()V: Line 390
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsAddIncomePage()V: Line 60
   * Goal 12. main.ClassUnderTestApogen.goToTransactionsWalletPage(Lcustom_classes/Id;)V: Line 525
   * Goal 13. main.ClassUnderTestApogen.goToWalletPageTransactionsPage()V: Line 404
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-3164);
      Id id0 = new Id(int0);
      WalletNames walletNames0 = WalletNames.COMPANY;
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames1 = WalletNames.COMPANY;
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      classUnderTestApogen0.goToTransactionsWalletPage(id0);
      classUnderTestApogen0.goToSetTotalPageTransactionsPage();
      int int1 = (-2532);
      Amount amount0 = new Amount(int1);
      classUnderTestApogen0.addProfitSetTotalPage(amount0);
      classUnderTestApogen0.goToAddIncomePageTransactionsPage();
      classUnderTestApogen0.goToTransactionsAddIncomePage();
      classUnderTestApogen0.goToWalletPageTransactionsPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      Goals goals0 = Goals.MUSEUM;
      classUnderTestApogen0.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(goals0, walletNames0);
      classUnderTestApogen0.goToPlanBasicSettingsPageCreatePlanAdvancedSettingsPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 2. main.ClassUnderTestApogen.editWalletWalletPage(Lcustom_classes/Id;)V: Line 469
   * Goal 3. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 4. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 5. main.ClassUnderTestApogen.goToTrashPageWalletPage()V: Line 543
   * Goal 6. main.ClassUnderTestApogen.goToWalletPageAddWalletPage()V: Line 347
   * Goal 7. main.ClassUnderTestApogen.goToWalletPageTrashPage()V: Line 126
   * Goal 8. main.ClassUnderTestApogen.hideHideWalletPage()V: Line 222
   * Goal 9. main.ClassUnderTestApogen.hideWalletWalletPage(Lcustom_classes/Id;)V: Line 562
   */

  @Test(timeout = 1001000)
  public void test5()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-583);
      Id id0 = new Id(int0);
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.PERSONAL;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.goToWalletPageAddWalletPage();
      classUnderTestApogen0.editWalletWalletPage(id0);
      classUnderTestApogen0.goToWalletPageAddWalletPage();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames1 = WalletNames.PERSONAL;
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      classUnderTestApogen0.hideWalletWalletPage(id0);
      classUnderTestApogen0.hideHideWalletPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
  }
}
