/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 27 20:54:55 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Email;
import custom_classes.Goals;
import custom_classes.Id;
import custom_classes.WalletNames;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 16 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addAccessGiveAccessToWalletPage(Lcustom_classes/Email;)V: Line 423
   * Goal 2. main.ClassUnderTestApogen.cancelRemoveEmailAccessPage()V: Line 236
   * Goal 3. main.ClassUnderTestApogen.closeAccessEmailPage()V: Line 158
   * Goal 4. main.ClassUnderTestApogen.confirmAndSaveCreatePlanAdvancedSettingsPage()V: Line 263
   * Goal 5. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 6. main.ClassUnderTestApogen.editWalletWalletPage(Lcustom_classes/Id;)V: Line 469
   * Goal 7. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 8. main.ClassUnderTestApogen.goToCreateNewPlanPageCreatePlanPage()V: Line 92
   * Goal 9. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 10. main.ClassUnderTestApogen.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(Lcustom_classes/Goals;Lcustom_classes/WalletNames;)V: Line 296
   * Goal 11. main.ClassUnderTestApogen.goToPlanPageCreatePlanBasicSettingsPage()V: Line 314
   * Goal 12. main.ClassUnderTestApogen.goToWalletPageHideWalletPage()V: Line 208
   * Goal 13. main.ClassUnderTestApogen.goToWalletPageViewPlanPage()V: Line 451
   * Goal 14. main.ClassUnderTestApogen.hideWalletWalletPage(Lcustom_classes/Id;)V: Line 562
   * Goal 15. main.ClassUnderTestApogen.manageWalletAccessWalletPage(Lcustom_classes/Id;)V: Line 585
   * Goal 16. main.ClassUnderTestApogen.removeAccessAccessEmailPage(Lcustom_classes/Email;)V: Line 174
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-2207);
      Id id0 = new Id(int0);
      Id id1 = new Id(id0.value);
      Email email0 = Email.ASD;
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.PRIVATE;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.manageWalletAccessWalletPage(id0);
      classUnderTestApogen0.addAccessGiveAccessToWalletPage(email0);
      classUnderTestApogen0.closeAccessEmailPage();
      classUnderTestApogen0.editWalletWalletPage(id1);
      WalletNames walletNames1 = WalletNames.PRIVATE;
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      classUnderTestApogen0.manageWalletAccessWalletPage(id1);
      classUnderTestApogen0.addAccessGiveAccessToWalletPage(email0);
      classUnderTestApogen0.removeAccessAccessEmailPage(email0);
      classUnderTestApogen0.cancelRemoveEmailAccessPage();
      classUnderTestApogen0.closeAccessEmailPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      Goals goals0 = Goals.CAR;
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(goals0, walletNames1);
      classUnderTestApogen0.confirmAndSaveCreatePlanAdvancedSettingsPage();
      classUnderTestApogen0.goToWalletPageViewPlanPage();
      classUnderTestApogen0.hideWalletWalletPage(id0);
      classUnderTestApogen0.goToWalletPageHideWalletPage();
  }

  //Test case number: 1
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 2. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 3. main.ClassUnderTestApogen.goToCreateNewPlanPageCreatePlanPage()V: Line 92
   * Goal 4. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 5. main.ClassUnderTestApogen.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(Lcustom_classes/Goals;Lcustom_classes/WalletNames;)V: Line 296
   * Goal 6. main.ClassUnderTestApogen.goToPlanBasicSettingsPageCreatePlanAdvancedSettingsPage()V: Line 278
   * Goal 7. main.ClassUnderTestApogen.goToPlanPageCreatePlanBasicSettingsPage()V: Line 314
   * Goal 8. main.ClassUnderTestApogen.hideHideWalletPage()V: Line 222
   * Goal 9. main.ClassUnderTestApogen.hideWalletWalletPage(Lcustom_classes/Id;)V: Line 562
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      int int0 = (-809);
      Id id0 = new Id(int0);
      WalletNames walletNames0 = WalletNames.COMPANY;
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      classUnderTestApogen0.hideWalletWalletPage(id0);
      classUnderTestApogen0.hideHideWalletPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      Goals goals0 = Goals.HOUSE;
      WalletNames walletNames1 = WalletNames.COMPANY;
      classUnderTestApogen0.goToPlanAdvancedSettingsCreatePlanBasicSettingsPage(goals0, walletNames1);
      classUnderTestApogen0.goToPlanBasicSettingsPageCreatePlanAdvancedSettingsPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
  }

  //Test case number: 2
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 2. main.ClassUnderTestApogen.goToCreateNewPlanPageCreatePlanPage()V: Line 92
   * Goal 3. main.ClassUnderTestApogen.goToGoalsPageWalletPage()V: Line 510
   * Goal 4. main.ClassUnderTestApogen.goToPlanPageCreatePlanBasicSettingsPage()V: Line 314
   * Goal 5. main.ClassUnderTestApogen.goToTrashPageWalletPage()V: Line 543
   * Goal 6. main.ClassUnderTestApogen.goToWalletPageAddWalletPage()V: Line 347
   * Goal 7. main.ClassUnderTestApogen.goToWalletPageTrashPage()V: Line 126
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      classUnderTestApogen0.goToWalletPageAddWalletPage();
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
      classUnderTestApogen0.goToGoalsPageWalletPage();
      classUnderTestApogen0.goToCreateNewPlanPageCreatePlanPage();
      classUnderTestApogen0.goToPlanPageCreatePlanBasicSettingsPage();
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editAddWalletPage(Lcustom_classes/WalletNames;)V: Line 333
   * Goal 2. main.ClassUnderTestApogen.goToAddWalletPageWalletPage()V: Line 492
   * Goal 3. main.ClassUnderTestApogen.goToTrashPageWalletPage()V: Line 543
   * Goal 4. main.ClassUnderTestApogen.goToWalletPageGiveAccessToWalletPage()V: Line 437
   * Goal 5. main.ClassUnderTestApogen.goToWalletPageTrashPage()V: Line 126
   * Goal 6. main.ClassUnderTestApogen.manageWalletAccessWalletPage(Lcustom_classes/Id;)V: Line 585
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames0 = WalletNames.PERSONAL;
      classUnderTestApogen0.editAddWalletPage(walletNames0);
      int int0 = 2296;
      Id id0 = new Id(int0);
      classUnderTestApogen0.manageWalletAccessWalletPage(id0);
      classUnderTestApogen0.goToWalletPageGiveAccessToWalletPage();
      classUnderTestApogen0.goToAddWalletPageWalletPage();
      WalletNames walletNames1 = WalletNames.COMPANY;
      classUnderTestApogen0.editAddWalletPage(walletNames1);
      classUnderTestApogen0.goToTrashPageWalletPage();
      classUnderTestApogen0.goToWalletPageTrashPage();
  }
}
